branches:
  # whitelist
  only:
    - master
clone_folder: c:\projects\nuclear
# Build worker image (VM template)
image:
 - Visual Studio 2015
 - Visual Studio 2017
configuration:
 - Release
platform:
 - x64
environment:
  matrix:
   - arch: Win64

matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- echo %generator%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%
build:
  project: c:\projects\nuclear\build\nuclear.sln
  verbosity: minimal
  parallel: true
